apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-skaffold-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: practice-skaffold
  template:
    metadata:
      labels:
        app: practice-skaffold
    spec:
      containers:
      - name: nginx
        image: DOCKERHUB_USER/practice-skaffold # 変更箇所 DOCKERHUB_USER